"""create torrents table

Revision ID: 0af2f93f1f43
Revises: 
Create Date: 2022-10-11 23:24:17.746472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0af2f93f1f43'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('torrents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('announce', sa.String(length=500), nullable=False),
    sa.Column('info', sa.JSON(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('announce_list', sa.PickleType(), nullable=True),
    sa.Column('creation_date', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('encoding', sa.String(length=100), nullable=True),
    sa.Column('publisher', sa.String(length=100), nullable=True),
    sa.Column('publisher_url', sa.String(length=100), nullable=True),
    sa.Column('comment', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('torrents')
    # ### end Alembic commands ###
