"""change info column type

Revision ID: 8e97ddf88c55
Revises: 0af2f93f1f43
Create Date: 2022-10-11 23:52:43.030298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e97ddf88c55'
down_revision = '0af2f93f1f43'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
